// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReyphillNunez_Ap1_P1.DAL;

#nullable disable

namespace ReyphillNunez_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.Cobros", b =>
                {
                    b.Property<int>("CobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Monto")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.HasKey("CobroId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.CobrosDetalles", b =>
                {
                    b.Property<int>("DetallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ValorCobrado")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.HasKey("DetallId");

                    b.HasIndex("CobroId");

                    b.ToTable("CobrosDetalles");
                });

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.Deudores", b =>
                {
                    b.Property<int>("DeudoresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeudoresId");

                    b.ToTable("Deudores");

                    b.HasData(
                        new
                        {
                            DeudoresId = 1,
                            Nombres = "Juan perez"
                        },
                        new
                        {
                            DeudoresId = 2,
                            Nombres = "Alaina Garcia"
                        },
                        new
                        {
                            DeudoresId = 3,
                            Nombres = "Reyphill Nuñez"
                        });
                });

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.HasKey("PrestamoId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.CobrosDetalles", b =>
                {
                    b.HasOne("ReyphillNunez_Ap1_P1.Models.Cobros", null)
                        .WithMany("CobrosDetalles")
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.Prestamos", b =>
                {
                    b.HasOne("ReyphillNunez_Ap1_P1.Models.Deudores", "Deudor")
                        .WithMany()
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("ReyphillNunez_Ap1_P1.Models.Cobros", b =>
                {
                    b.Navigation("CobrosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
